name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'ml-recommendation-cicd' # TODO: update Google Cloud project id
  GAR_LOCATION: 'asia-south1' # Artifact Registry location for Mumbai
  SERVICE: 'book-recommendation-api' # Cloud Run service name
  REGION: 'asia-south1' # Cloud Run service region

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # BEGIN - Docker auth and build

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: _json_key
          password: '${{ secrets.GCP_CREDENTIALS }}'
          registry: 'asia-south1-docker.pkg.dev' # Updated registry for Mumbai region

      - name: Build and push Docker image
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          IMAGE_NAME=asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/gmo9recommendation/my-flask-app
          docker build --build-arg DATABASE_URL=$DATABASE_URL -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # END - Docker auth and build

      - name: Deploy to Cloud Run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          IMAGE_NAME=asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/gmo9recommendation/my-flask-app
          gcloud run deploy my-flask-app \
            --image $IMAGE_NAME \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --update-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}
